---
- block:

  - name: "Set UI feature state"
    set_fact:
      ui_state: "present"
    when: feature_ui_enabled|bool

  - name: "Load cluster API groups"
    set_fact:
      api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

  - when: "'route.openshift.io' in api_groups"
    block:
      - name: "Enable OpenShift cluster environment"
        set_fact:
          openshift_cluster: true

      - name: "Obtain k8s cluster version"
        set_fact:
          k8s_cluster_version: "{{ lookup('k8s', cluster_info='version').kubernetes.gitVersion }}"

  - name: "Setup the webhook secret"
    k8s:
      state: present
      definition: "{{ lookup('template', 'secret-webhook-server-secret.yml.j2') }}"

  - when:
      - feature_auth_enabled|bool
      - feature_auth_provider == "keycloak"
    block:
      - name: "Setup Keycloak PostgreSQL PersistentVolume"
        k8s:
          state: present
          definition: "{{ lookup('template', 'persistentvolumeclaim-keycloak-postgresql.yml.j2') }}"

      - name: "Check if Keycloak PostgreSQL Secret exists already so we don't update it"
        k8s_info:
          api_version: v1
          kind: Secret
          name: "{{ keycloak_database_secret_name }}"
          namespace: "{{ app_namespace }}"
        register: keycloak_database_secret_status

      - when: (keycloak_database_secret_status.resources | length) == 0
        block:
          - name: "Generate random values for Keycloak PostgreSQL username and password"
            set_fact:
              keycloak_database_db_username: "user-{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=4') }}"
              keycloak_database_db_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16') }}"

          - name: "Encode Keycloak PostgreSQL username and password"
            set_fact:
              keycloak_database_db_username_b64: "{{ keycloak_database_db_username | b64encode }}"
              keycloak_database_db_password_b64: "{{ keycloak_database_db_password | b64encode }}"

          - name: "Setup Keycloak PostgreSQL Secret"
            k8s:
              state: present
              definition: "{{ lookup('template', 'secret-keycloak-postgresql.yml.j2') }}"

      - name: "Setup Keycloak PostgreSQL Service"
        k8s:
          state: present
          definition: "{{ lookup('template', 'service-keycloak-postgresql.yml.j2') }}"

      - name: "Setup Keycloak PostgreSQL Deployement"
        k8s:
          state: present
          definition: "{{ lookup('template', 'deployment-keycloak-postgresql.yml.j2') }}"

      - name: "Check if Keycloak SSO Secret exists already so we don't update it"
        k8s_info:
          api_version: v1
          kind: Secret
          name: "{{ keycloak_sso_secret_name }}"
          namespace: "{{ app_namespace }}"
        register: keycloak_sso_secret_status

      - when: (keycloak_sso_secret_status.resources | length) == 0
        block:
          - name: "Generate random values for Keycloak PostgreSQL and SSO username and password"
            set_fact:
              keycloak_database_db_username: "user-{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=4') }}"
              keycloak_database_db_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16') }}"
              keycloak_sso_admin_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16') }}"

          - name: "Encode Keycloak PostgreSQL and SSO username and password"
            set_fact:
              keycloak_database_db_username_b64: "{{ keycloak_database_db_username | b64encode }}"
              keycloak_database_db_password_b64: "{{ keycloak_database_db_password | b64encode }}"
              keycloak_sso_admin_password_b64: "{{ keycloak_sso_admin_password | b64encode }}"

          - name: "Setup Keycloak SSO Secret"
            k8s:
              state: present
              definition: "{{ lookup('template', 'secret-keycloak-sso.yml.j2') }}"

      - name: "Setup Keycloak SSO ConfigMap"
        k8s:
          state: present
          definition: "{{ lookup('template', 'configmap-keycloak-sso.yml.j2') }}"

      - name: "Setup Keycloak SSO Service"
        k8s:
          state: present
          definition: "{{ lookup('template', 'service-keycloak-sso.yml.j2') }}"

      - name: "Setup Keycloak SSO Deployement"
        k8s:
          state: present
          definition: "{{ lookup('template', 'deployment-keycloak-sso.yml.j2') }}"

  - name: "Setup Tackle Hub API Database PersistentVolumeClaim"
    k8s:
      state: present
      definition: "{{ lookup('template', 'persistentvolumeclaim-hub-api-database.yml.j2') }}"

  - name: "Setup Tackle Hub API Bucket PersistentVolumeClaim"
    k8s:
      state: present
      definition: "{{ lookup('template', 'persistentvolumeclaim-hub-api-bucket.yml.j2') }}"

  - name: "Setup Tackle Hub API Service"
    k8s:
      state: present
      definition: "{{ lookup('template', 'service-hub-api.yml.j2') }}"

  - name: "Setup Tackle Hub API Deployement"
    k8s:
      state: present
      definition: "{{ lookup('template', 'deployment-hub-api.yml.j2') }}"

  - name: "Setup PathFinder PostgreSQL PersistentVolume"
    k8s:
      state: present
      definition: "{{ lookup('template', 'persistentvolumeclaim-pathfinder-postgresql.yml.j2') }}"

  - name: "Check if PathFinder PostgreSQL Secret exists already so we don't update it"
    k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ pathfinder_database_secret_name }}"
      namespace: "{{ app_namespace }}"
    register: pathfinder_database_secret_status

  - when: (pathfinder_database_secret_status.resources | length) == 0
    block:
      - name: "Generate random values for PathFinder PostgreSQL username and password"
        set_fact:
          pathfinder_database_db_username: "user-{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=4') }}"
          pathfinder_database_db_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16') }}"

      - name: "Encode PathFinder PostgreSQL username and password"
        set_fact:
          pathfinder_database_db_username_b64: "{{ pathfinder_database_db_username | b64encode }}"
          pathfinder_database_db_password_b64: "{{ pathfinder_database_db_password | b64encode }}"

      - name: "Setup PathFinder PostgreSQL Secret"
        k8s:
          state: present
          definition: "{{ lookup('template', 'secret-pathfinder-postgresql.yml.j2') }}"

  - name: "Setup PathFinder PostgreSQL Service"
    k8s:
      state: present
      definition: "{{ lookup('template', 'service-pathfinder-postgresql.yml.j2') }}"

  - name: "Setup PathFinder PostgreSQL Deployement"
    k8s:
      state: present
      definition: "{{ lookup('template', 'deployment-pathfinder-postgresql.yml.j2') }}"

  - name: "Setup PathFinder API Service"
    k8s:
      state: present
      definition: "{{ lookup('template', 'service-pathfinder-api.yml.j2') }}"

  - name: "Setup PathFinder API Deployement"
    k8s:
      state: present
      definition: "{{ lookup('template', 'deployment-pathfinder-api.yml.j2') }}"

  - when: feature_ui_enabled|bool
    block:
      - name: "Setup Tackle UI Service"
        k8s:
          state: present
          definition: "{{ lookup('template', 'service-ui.yml.j2') }}"

      - name: "Setup Tackle UI Deployement"
        k8s:
          state: present
          definition: "{{ lookup('template', 'deployment-ui.yml.j2') }}"

      - when: not openshift_cluster|bool
        k8s:
          state: present
          definition: "{{ lookup('template', 'ingress-ui.yml.j2') }}"

      - when: openshift_cluster|bool
        k8s:
          state: present
          definition: "{{ lookup('template', 'route-ui.yml.j2') }}"
