# permissions for end users to view tackles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tackle-viewer-role
rules:
- apiGroups:
  - tackle.io
  resources:
  - tackles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tackle.io
  resources:
  - tackles/status
  verbs:
  - get
