# permissions for end users to edit tackles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tackle-editor-role
rules:
- apiGroups:
  - tackle.konveyor.io
  resources:
  - tackles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tackle.konveyor.io
  resources:
  - tackles/status
  verbs:
  - get
